# Generated by Django 3.1.7 on 2021-03-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20210311_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='g1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='g2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='p',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
