# Generated by Django 3.1.7 on 2021-03-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20210325_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('p', models.CharField(max_length=500)),
                ('g1', models.CharField(max_length=500)),
                ('g2', models.CharField(max_length=500)),
                ('g3', models.CharField(max_length=500)),
                ('g4', models.CharField(max_length=500)),
                ('omega', models.CharField(max_length=500)),
                ('theta', models.CharField(max_length=500)),
            ],
        ),
    ]
