# Generated by Django 3.2 on 2021-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
