# Generated by Django 3.2 on 2021-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20210420_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
