# Generated by Django 3.2 on 2021-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('p', models.CharField(max_length=500)),
                ('g1', models.CharField(max_length=500)),
                ('g2', models.CharField(max_length=500)),
                ('g3', models.CharField(max_length=500)),
                ('g4', models.CharField(max_length=500)),
                ('A1', models.CharField(max_length=500)),
                ('B1', models.CharField(max_length=500)),
                ('x2', models.CharField(max_length=500)),
                ('a2', models.CharField(max_length=500)),
                ('b2', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('bankid', models.CharField(max_length=500)),
                ('bankname', models.CharField(max_length=500)),
            ],
        ),
    ]
